/* NDOYE Amadou Lamine */
module drawMeASheep{
	module generated{

		module entity{
			struct Point {
			double x;
			double y;	
			};
			
			typedef sequence <Point> PointSet;


			interface Drawing {
				double getSurface();
				double getPerimeter();
				void translate(in Point translationPoint);
				void homothetie(in double x);
				void rotate(in double angle);
				void centralSymetric(in Point p);
				void axialSymetric(in Point p1, in Point p2);
			};

			interface Polygone : Drawing {
				readonly attribute PointSet points;
			};
			interface Line : Drawing {
				readonly attribute Point a;
				readonly attribute Point b;	
	
			};
			interface Cercle : Drawing {
				readonly attribute double rayon;	
				readonly attribute Point center;

			};
			interface Ellipse : Cercle {
				readonly attribute double largeur;
			};

			typedef sequence <Drawing> DrawingSet;
			typedef sequence <Drawing> DrawingMap;

			interface DrawingGroup:Drawing {
				readonly attribute DrawingSet Drawings;
			
			 };
		};

		module manager{
			typedef sequence <double> Params;
			interface DrawingManager{
				readonly attribute entity::DrawingMap map;
				entity::Drawing createDrawing( in string name ,in Params params);
				long add( in entity::Drawing a);
				boolean isFull();
				double getAvailableSurface();
				string getDrawings();
			};

		};
	};	
	
};
