module drawMeASheep{

	struct Point {
		double x;
		double y;
	};

	typedef sequence <Point> PointSet;


	interface Drawing {
		double getSurface();
		double getPerimeter();
		void translate(in double x);
		void homothetie(in double x);
		void rotate(in double angle);
		void centralSymetric(in Point p);
		void axialSymetric(in Point p1, in Point p2);
	 };

	interface Polygone : Drawing {
		readonly attribute PointSet points;
	};
	interface Line : Drawing {
		readonly attribute Point a;
		readonly attribute Point b;	
	
	};
	interface Cercle : Drawing {
		readonly attribute double rayon;	

	};
	interface Ellipse : Drawing {
		readonly attribute PointSet points;
	};

	typedef sequence <Drawing> DrawingSet;
	typedef sequence <Drawing> DrawingMap;

	interface DrawingGroup:Drawing {
		readonly attribute DrawingSet Drawings;
		
	 };
	interface DrawingManager {
		readonly attribute DrawingMap map;
		boolean add( in Drawing d);
		boolean isFull();
		double getAvailableSurgace();

	};
		
	
};
