// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "Test.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



Account_ptr Account_Helper::_nil() {
  return ::Account::_nil();
}

::CORBA::Boolean Account_Helper::is_nil(::Account_ptr p) {
  return ::CORBA::is_nil(p);

}

void Account_Helper::release(::Account_ptr p) {
  ::CORBA::release(p);
}

void Account_Helper::marshalObjRef(::Account_ptr obj, cdrStream& s) {
  ::Account::_marshalObjRef(obj, s);
}

Account_ptr Account_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Account::_unmarshalObjRef(s);
}

void Account_Helper::duplicate(::Account_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Account_ptr
Account::_duplicate(::Account_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Account_ptr
Account::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Account_ptr
Account::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Account_ptr
Account::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Account _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Account* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Account;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Account::_PD_repoId = "IDL:Account:1.0";


_objref_Account::~_objref_Account() {
  
}


_objref_Account::_objref_Account(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Account::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_Account::_ptrToObjRef(const char* id)
{
  if (id == ::Account::_PD_repoId)
    return (::Account_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Account::_PD_repoId))
    return (::Account_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Account::send

// Proxy call descriptor class. Mangled signature:
//  void_i_cdouble
class _0RL_cd_ef2ddd5f39f056ad_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_ef2ddd5f39f056ad_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
};

void _0RL_cd_ef2ddd5f39f056ad_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_ef2ddd5f39f056ad_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

const char* const _0RL_cd_ef2ddd5f39f056ad_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_ef2ddd5f39f056ad_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_ef2ddd5f39f056ad_00000000* tcd = (_0RL_cd_ef2ddd5f39f056ad_00000000*)cd;
  _impl_Account* impl = (_impl_Account*) svnt->_ptrToInterface(Account::_PD_repoId);
  impl->send(tcd->arg_0);


}

void _objref_Account::send(::CORBA::Double amount)
{
  _0RL_cd_ef2ddd5f39f056ad_00000000 _call_desc(_0RL_lcfn_ef2ddd5f39f056ad_10000000, "send", 5);
  _call_desc.arg_0 = amount;

  _invoke(_call_desc);



}

_pof_Account::~_pof_Account() {}


omniObjRef*
_pof_Account::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_Account(ior, id);
}


::CORBA::Boolean
_pof_Account::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Account::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_Account _the_pof_Account;

_impl_Account::~_impl_Account() {}


::CORBA::Boolean
_impl_Account::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "send")) {

    _0RL_cd_ef2ddd5f39f056ad_00000000 _call_desc(_0RL_lcfn_ef2ddd5f39f056ad_10000000, "send", 5, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_Account::_ptrToInterface(const char* id)
{
  if (id == ::Account::_PD_repoId)
    return (::_impl_Account*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Account::_PD_repoId))
    return (::_impl_Account*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_Account::_mostDerivedRepoId()
{
  return ::Account::_PD_repoId;
}

POA_Account::~POA_Account() {}

